### ISSUE TITLE
setiap reload graph sebelumnya tetap muncul

### ISSUE THREAD

**Issue by alba054** [yukiao/edge-coloring-app#12]
tiap kali reload page graph sebelumya masih ada

**Comment by yukiao** [comment]
Secara default, graphnya tetap akan merender kembali graph sebelumnya karena memanfaatkan fitur autosave. Kedepannya mungkin akan ditambahkan fitur untuk menonaktifkan fitur autosavenya

**Comment by alba054** [comment]
fix
